### ISSUE TITLE
Relative paths

### ISSUE THREAD

**Issue by gobeli** [Angular-RU/angular-nest-starter#2]
Hi there,

There are some path references which are a bit strange.
Firstly the static path to the dist seems to be one level to low (should be `'../dist'` in my opinion)
https://github.com/Angular-RU/angular-nest-starter/blob/e98c61dd9b7b05036d412b0ad12c04c3fea67261/server/main.ts#L16

In the `not-found-exception.filter` there is a reference to a index.html at the root level which does not exist...
https://github.com/Angular-RU/angular-nest-starter/blob/e98c61dd9b7b05036d412b0ad12c04c3fea67261/server/common/filters/not-found-exception.filter.ts#L9

**Comment by pumano** [comment]
Hi, @gobeli 
1) it's because it is in `/server` folder, but generated javascript code moved to 
`/dist` for frontend and `/dist/server` for backend. If you want to change it, just change output path in tsconfig.json for backend and frontend
2) same scenario it is because not-found-exception in `server/common/filters` path

**Comment by gobeli** [comment]
Ohh got you, I was struggling with it in Dev mode, but those are both irrelevant in Dev mode anyway.
